### ISSUE TITLE
Ändring av kontakt för stadsområde

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#232]
Försöker ändra befintligt kontakt för ett stadsområde. Ändringen slår inte igenom, istället skapas en ny kontakt för valt stadsområde.

**Comment by rbolton479** [comment]
I will check this ola but i'm pretty sure this is how it is and this is how it was in the old version. We came across it in our testing during december. 
If it is the same thing that we saw earlier i'm afraid it's not fixable because of how each contact is handled in the list. I will get back to you with more information.

**Comment by olajoh1** [comment]
Ej åtgärd
